server:
  port: 8001
  servlet:
    context-path: /jpa
spring:
  application:
    name: springboot-jpa
  datasource:
    #type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jpa?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8
    username: root
    password: 123456
    hikari:
      minimum-idle: 10 #最小空闲连接，默认10
      maximum-pool-size: 20 #最大连接数
      idle-timeout: 600000 #空闲连接超时时间，默认600000(10分钟)
      max-lifetime: 540000 #连接最大存活时间，默认30分钟
      connection-timeout: 60000 #连接超时时间，默认30秒
      connection-test-query: SELECT 1 #测试连接是否可用查询语句
  jpa:
    hibernate:
      ddl-auto: update #数据库表生成策略
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true #控制台显示sql语句
    database: mysql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
